import type { Category, Product, Order } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Electronics & Tech',
    slug: 'electronics',
    image: 'category-electronics',
    description: 'Connect with the future. Discover the latest in smartphones, laptops, televisions, and gadgets. Innovation and performance from market-leading brands, all in one place.',
  },
  {
    id: '2',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    image: 'category-home',
    description: 'Create the space of your dreams. Refresh every corner of your home with our selection of furniture, decor, appliances, and kitchen utensils. Quality and style for your everyday life.',
  },
  {
    id: '3',
    name: 'Fashion & Accessories',
    slug: 'fashion',
    image: 'category-fashion',
    description: 'Define your style, without limits. Find the latest trends in clothing, footwear, and accessories for the whole family. Dress with confidence, whatever the occasion.',
  },
  {
    id: '4',
    name: 'Books & Entertainment',
    slug: 'books',
    image: 'category-books',
    description: 'Your next great story awaits. Immerse yourself in a universe of books, movies, TV shows, and music. Adventure, knowledge, and fun are just a click away.',
  },
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'ProBook X1 Laptop',
    slug: 'probook-x1-laptop',
    category: 'electronics',
    images: ['product-laptop-1', 'product-laptop-2'],
    price: 1299.99,
    description: 'The ProBook X1 is the pinnacle of performance and portability. With the latest-gen processor, stunning 4K display, and all-day battery life, it\'s built for professionals on the go.',
    rating: 4.8,
    reviewCount: 256,
    tags: ['laptop', 'work', 'high-performance'],
  },
  {
    id: 'prod_2',
    name: 'Galaxy S25 Smartphone',
    slug: 'galaxy-s25-smartphone',
    category: 'electronics',
    images: ['product-smartphone-1', 'product-smartphone-2'],
    price: 899.00,
    description: 'Experience the future of mobile with the Galaxy S25. Featuring a pro-grade camera system, an immersive dynamic display, and groundbreaking AI features.',
    rating: 4.9,
    reviewCount: 1024,
    tags: ['smartphone', 'mobile', 'camera'],
  },
    {
    id: 'prod_3',
    name: 'Aura Wireless Headphones',
    slug: 'aura-wireless-headphones',
    category: 'electronics',
    images: ['product-headphones-1'],
    price: 249.99,
    description: 'Immerse yourself in pure, uninterrupted sound. The Aura Wireless Headphones offer industry-leading noise cancellation and high-fidelity audio in a comfortable, stylish design.',
    rating: 4.7,
    reviewCount: 512,
    tags: ['audio', 'headphones', 'noise-cancelling'],
  },
    {
    id: 'prod_10',
    name: 'Vision Pro Camera',
    slug: 'vision-pro-camera',
    category: 'electronics',
    images: ['product-camera-1'],
    price: 1999.99,
    description: 'Capture life in stunning detail with the Vision Pro Camera. A favorite among professionals for its unmatched image quality, robust build, and intuitive controls.',
    rating: 4.9,
    reviewCount: 432,
    tags: ['camera', 'photography', 'professional'],
  },
  {
    id: 'prod_4',
    name: 'Nordic Comfort Sofa',
    slug: 'nordic-comfort-sofa',
    category: 'home-kitchen',
    images: ['product-sofa-1'],
    price: 999.50,
    description: 'A masterpiece of minimalist design and maximum comfort. The Nordic sofa is the perfect centerpiece for any modern living room.',
    rating: 4.6,
    reviewCount: 128,
    tags: ['furniture', 'sofa', 'living-room'],
  },
  {
    id: 'prod_5',
    name: 'Helia Desk Lamp',
    slug: 'helia-desk-lamp',
    category: 'home-kitchen',
    images: ['product-lamp-1'],
    price: 79.99,
    description: 'Illuminate your workspace with the elegant Helia Desk Lamp. Features adjustable brightness and color temperature to suit any mood or task.',
    rating: 4.5,
    reviewCount: 300,
    tags: ['lighting', 'lamp', 'office'],
  },
    {
    id: 'prod_11',
    name: 'Fusion Blender Pro',
    slug: 'fusion-blender-pro',
    category: 'home-kitchen',
    images: ['product-blender-1'],
    price: 129.00,
    description: 'Unleash your culinary creativity. The Fusion Blender Pro handles everything from smoothies to soups with its powerful motor and precision blades.',
    rating: 4.8,
    reviewCount: 678,
    tags: ['kitchen', 'appliance', 'blender'],
  },
  {
    id: 'prod_6',
    name: 'Classic Cotton T-Shirt',
    slug: 'classic-cotton-t-shirt',
    category: 'fashion',
    images: ['product-tshirt-1'],
    price: 29.99,
    description: 'The perfect t-shirt does exist. Made from 100% premium Pima cotton, it offers a soft feel and a fit that\'s just right. Available in 15 colors.',
    rating: 4.7,
    reviewCount: 2300,
    tags: ['apparel', 't-shirt', 'basics'],
  },
  {
    id: 'prod_7',
    name: 'Urban Slim-Fit Jeans',
    slug: 'urban-slim-fit-jeans',
    category: 'fashion',
    images: ['product-jeans-1'],
    price: 89.99,
    description: 'A modern take on a timeless classic. Our Urban Slim-Fit Jeans are crafted with stretch denim for all-day comfort and a silhouette that looks great on everyone.',
    rating: 4.6,
    reviewCount: 940,
    tags: ['apparel', 'jeans', 'denim'],
  },
    {
    id: 'prod_12',
    name: 'Strider Running Sneakers',
    slug: 'strider-running-sneakers',
    category: 'fashion',
    images: ['product-sneakers-1'],
    price: 119.99,
    description: 'Engineered for performance, designed for style. The Strider sneakers provide responsive cushioning and a breathable upper to keep you going mile after mile.',
    rating: 4.7,
    reviewCount: 1150,
    tags: ['footwear', 'sneakers', 'running'],
  },
  {
    id: 'prod_8',
    name: 'The Last Voyager (Novel)',
    slug: 'the-last-voyager-novel',
    category: 'books',
    images: ['product-novel-1'],
    price: 14.99,
    description: 'A thrilling sci-fi epic about the last human ship searching for a new home among the stars. A must-read for fans of space opera.',
    rating: 4.9,
    reviewCount: 3450,
    tags: ['book', 'sci-fi', 'fiction'],
  },
  {
    id: 'prod_9',
    name: 'Artisan Breads Cookbook',
    slug: 'artisan-breads-cookbook',
    category: 'books',
    images: ['product-cookbook-1'],
    price: 24.99,
    description: 'Master the art of bread making with this comprehensive guide. Features over 100 recipes from simple loaves to complex sourdoughs.',
    rating: 4.8,
    reviewCount: 780,
    tags: ['book', 'cookbook', 'baking'],
  },
    {
    id: 'prod_13',
    name: 'Timeless Grooves - Vinyl',
    slug: 'timeless-grooves-vinyl',
    category: 'books',
    images: ['product-vinyl-1'],
    price: 34.99,
    description: 'A curated collection of soul and funk classics on 180-gram vinyl. The perfect soundtrack for any occasion, delivering warm, rich audio.',
    rating: 5.0,
    reviewCount: 250,
    tags: ['music', 'vinyl', 'soul'],
  },
];


export const orders: Order[] = [
    {
        id: 'ORD-001',
        date: '2023-10-26',
        total: 1549.98,
        status: 'Delivered',
        items: [
            {...products[0], quantity: 1, image: products[0].images[0]},
            {...products[2], quantity: 1, image: products[2].images[0]},
        ]
    },
    {
        id: 'ORD-002',
        date: '2023-11-15',
        total: 119.98,
        status: 'Shipped',
        items: [
            {...products[5], quantity: 2, image: products[5].images[0]},
        ]
    },
    {
        id: 'ORD-003',
        date: '2023-12-01',
        total: 39.98,
        status: 'Pending',
        items: [
            {...products[10], quantity: 1, image: products[10].images[0]},
            {...products[11], quantity: 1, image: products[11].images[0]},
        ]
    }
]
